import type { Metadata } from "next";
import "../globals.css";

import { ThemeProvider } from "@/components/theme-provider"
import { Martian_Mono, Geist_Mono } from 'next/font/google';

const martian_mono = Martian_Mono({
  subsets: ['latin'],
  weight: ['200'],
  variable: '--display-family',
});

const geist_mono = Geist_Mono({
  subsets: ['latin'],
  weight: ['300'],
  variable: '--text-family',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${martian_mono.variable} ${geist_mono.variable}`} suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
