import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar"
import { SiteHeader } from "@/components/site-header"
import { ThemeProvider } from "@/components/theme-provider"
import { AuthGuard } from "@/components/auth-guard";
import { Toaster } from 'sonner'

import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"

import { Jost } from "next/font/google"

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // podes ajustar conforme quiseres
  variable: "--font-jost",
})

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f0f0f" }, // ou outra cor escura
  ],
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={jost.className} suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
                } as React.CSSProperties
              }
            >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                <div className="flex flex-1 flex-col">
                  <div className="@container/main flex flex-1 flex-col gap-2 container max-w-6xl mx-auto">
                    <AuthGuard>
                      {children}
                    </AuthGuard>
                    <Toaster richColors position="top-center" />
                  </div>
                </div>
              </SidebarInset>
            </SidebarProvider>

          </ThemeProvider>

      </body>
    </html>
  );
}
