import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar"
import { SiteHeader } from "@/components/site-header"
import { ThemeProvider } from "@/components/theme-provider"

import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"

import { Martian_Mono, Geist_Mono } from 'next/font/google';

const martian_mono = Martian_Mono({
  subsets: ['latin'],
  weight: ['200'],
  variable: '--display-family',
});

const geist_mono = Geist_Mono({
  subsets: ['latin'],
  weight: ['300'],
  variable: '--text-family',
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f0f0f" }, // ou outra cor escura
  ],
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${martian_mono.variable} ${geist_mono.variable}`} suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider
              style={
                {
                  "--sidebar-width": "calc(var(--spacing) * 72)",
                  "--header-height": "calc(var(--spacing) * 12)",
                } as React.CSSProperties
              }
            >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                <div className="flex flex-1 flex-col">
                  <div className="@container/main flex flex-1 flex-col gap-2 container max-w-6xl mx-auto">
                    {children}
                  </div>
                </div>
              </SidebarInset>
            </SidebarProvider>

          </ThemeProvider>

      </body>
    </html>
  );
}
